name: Deploy Laravel to DigitalOcean
on:
  push:
    branches: [staging]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create .env file
        run: echo "${{ secrets.LARAVEL_ENV }}" > .env

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_POS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.DO_POS_SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          rsync -avz --delete \
            --exclude='.git*' \
            --exclude='tests' \
            --exclude='phpunit.xml' \
            --exclude='.env.example' \
            ./ root@${{ secrets.DO_POS_SERVER_IP }}:/var/www/pos/

      - name: Run Deployment Commands
        run: |
          ssh root@${{ secrets.DO_POS_SERVER_IP }} "cd /var/www/pos && \
          php artisan down && \
          php artisan migrate --force && \
          php artisan config:cache && \
          php artisan route:cache && \
          php artisan view:cache && \
          chown -R www-data:www-data . && \
          php artisan up"
